// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SAN_DestinationAnimation","status":true,"description":"目標地点アニメーション 1.0.0\r\nマップ上の目標地点にアニメーションを表示します。","parameters":{"Visible":"ON","AnimationID":"1","Scale":"100","Opacity":"255","Loop":"ON"}}
];
